run:
	gcc hw3named.c -o hw3 -lrt -lpthread -Wall -g
	gcc wholesaler.c -o wholesaler -lrt -lpthread -Wall -g
	gcc chef.c -o chef -lrt -lpthread -Wall -g
	gcc pusher.c -o pusher -lrt -lpthread -Wall -g

clean:
	rm wholesaler chef pusher hw3